add_newline = false
format = """
[â–‘â–’â–“](#a3aed2)\
[ îœ‘ ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
\n$character"""

palette = "tokyonight"
right_format = """$all"""
command_timeout = 1000

# Ğ¦Ğ²ĞµÑ‚Ğ° Ğ¼Ğ¾Ğ´ÑƒĞ»ĞµĞ¹ Ğ² ÑÑ‚Ğ¸Ğ»Ğµ TokyoNight
[directory]
style = "bold blue"
read_only = " ï€£"
read_only_style = "red"
truncate_to_repo = false
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "


[character]
success_symbol = "[â€¢â–¶](bold sky)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[âŸ¨NâŸ©>>>](bold pink)"

[git_branch]
style = "bold sky"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = "peach"
format = '([ $all_status$ahead_behind]($style) )'
conflicted = "ï‘¿ "
ahead = "ï¢Ã—${count}"
behind = "ï£Ã—${count}"
diverged = "ï¢${ahead_count} ï£${behind_count}"
untracked = "ï„¨Ã—${count}"
stashed = "ï€œÃ—${count}"
modified = "ï‘„Ã—${count}"
staged = "ï§Ã—${count}"
renamed = "ï¡Ã—${count}"
deleted = "ï€”Ã—${count}"

[git_metrics]
disabled = false
format = '[ +$added -$deleted ](teal)'

[cmd_duration]
min_time = 500
style = "teal"
format = "[â± $duration]($style) "

[status]
disabled = false
style = "red"
symbol = "âœ—"
format = "[$symbol $status]($style) "

[jobs]
style = "peach"
symbol = "ï€“ "
number_threshold = 1
format = "[$symbol$number]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "subtext1"
format = "[$time]($style) "

[username]
show_always = false
style_user = "green"
style_root = "red"
format = "[$user]($style) "

[hostname]
ssh_only = true
style = "yellow"
format = "[@$hostname]($style) "

[sudo]
style = "maroon"
symbol = "ï„ª "
format = "[$symbol]($style) "
disabled = false

[aws]
style = "bold blue"
symbol = "îŒ½ "
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style) '

[docker_context]
disabled = true

[nodejs]
format = "[îœ˜ $version]($style) "
style = "green"

[python]
format = "[î˜† $version$virtualenv]($style) "
style = "yellow"

[rust]
format = "[î¨ $version]($style) "
style = "peach"

[golang]
format = "[î˜§ $version]($style) "
style = "cyan"

[package]
style = "mauve"
format = "[ğŸ“¦ $version]($style) "

[battery]
disabled = false
full_symbol = "ï‰€ "
charging_symbol = "ï‡¦ "
discharging_symbol = "ï‰‚ "
format = "[$symbol$percentage]($style) "
[[battery.display]]
threshold = 20
style = "red"
[[battery.display]]
threshold = 50
style = "yellow"
[[battery.display]]
threshold = 100
style = "green"

[kubernetes]
symbol = 'â˜¸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "kamradsmeshnyavy", symbol = "ïˆ³ " },
]

[palettes.tokyonight]
rosewater = "#f7768e"
flamingo  = "#ff9e64"
pink      = "#bb9af7"
mauve     = "#9d7cd8"
red       = "#f7768e"
maroon    = "#db4b4b"
peach     = "#ff9e64"
yellow    = "#e0af68"
green     = "#9ece6a"
teal      = "#73daca"
sky       = "#7dcfff"
sapphire  = "#2ac3de"
blue      = "#7aa2f7"
lavender  = "#c0caf5"
text      = "#c0caf5"
subtext1  = "#a9b1d6"
subtext0  = "#9aa5ce"
overlay2  = "#737aa2"
overlay1  = "#565f89"
overlay0  = "#414868"
surface2  = "#3b4261"
surface1  = "#292e42"
surface0  = "#24283b"
base      = "#1f2335"
mantle    = "#1a1b26"
crust     = "#15161e"